version: '3.7'
services:
  sushi-takeout-db:
    container_name: sushi-takeout-db
    image: postgres:14.0
    ports:
      - '5443:5432' # 他のプロジェクトとportが被らないように5403:5432 -> '5443:5432'に変更
    volumes:
      - sushi-takeout-db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: prisma2020
      POSTGRES_DB: prisma
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      TZ: 'Asia/Tokyo'
  sushi-takeout-test-db:
    container_name: sushi-takeout-test-db
    image: postgres:14.0
    ports:
      - '5442:5432' # 他のプロジェクトとportが被らないように5403:5432 -> '5443:5432'に変更
    volumes:
      - sushi-takeout-test-db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: prisma2020
      POSTGRES_DB: prisma
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      TZ: 'Asia/Tokyo'

volumes:
  sushi-takeout-db-store:
    driver: local
  sushi-takeout-test-db-store:
    driver: local
